### PR TITLE
Songbook chapter/songs edit update function.

### PR DESCRIPTION
**Pull request by shortnd**
Added functionality to add update and add songs to chapters. Also trying to implement some testing now.. to verify everything works and will start setting up CI eventually

### CODE REVIEW

**Comment by shortnd** [comment]
Forgot to add image upload

**Comment by shortnd** [comment]
Will do it soon then reopen

**Comment by shortnd** [comment]
Chapters need to have ids

**Comment by tacoman** [comment]
@galenriley this looks good. We won't merge it into master without your go-ahead since that would update your server and we know you're busy right now, though.

@shortnd if you want to get this merged in to something that's production now we could re-create the ngsdetroit branch to represent the current state of our server, and then you'd have my full permission to update Heroku.

**Pull request closed without merging**
